AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/**/*
    - db/**/*
    - lib/**/*
    - node_modules/**/*
    - config/**/*.rb
    - Rakefile
    - .pryrc
    - vendor/**/*

Metrics/LineLength:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - app/**/concerns/**/*.rb

Style/SignalException:
  EnforcedStyle: semantic

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
